meta_product_name: "My Name Is Bernard"
meta_title: "MY NAME IS BERNARD - Warming and trendy coliving for Lille city-dwellers"
meta_description: "Rent your room in a fully furnished distinguished house & live with your fellows"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
