meta_product_name: "sharry"
meta_title: "sharry - Warming and trendy coliving for Lille city-dwellers"
meta_description: "Rent your room in a fully furnished distinguished house & live with your fellows"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
meta_fb: "241991959577159"                     
