meta_product_name: "My Name Is Bernard"
meta_title: "MY NAME IS BERNARD coliving - Colocation premium pour jeune actif"
meta_description: "My Name Is Bernard propose des chambres en coliving à Lille pour jeune actif dans des maisons d’exception. C’est à mi chemin entre la colocation & l'hôtel."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
