meta_product_name: "sharry"
meta_title: "sharry - Coliving in Lille"
meta_description: "Rent your room in a fully furnished distinguished house & live with your fellows"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
